// <auto-generated />
namespace WayToGo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class thatmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(thatmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202201201605296_that migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
